# Generated by Django 5.2.17 on 2026-09-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'JOURNALIST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'JOURNALIST'}, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(limit_choices_to=models.Q(('role__in', ['JOURNALIST', 'EDITOR'])), on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EDITOR'}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'JOURNALIST'}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
