# Generated by Django 5.2.17 on 2026-09-18 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('JOURNALIST', 'Journalist'), ('EDITOR', 'Editor'), ('PUBLISHER', 'Publisher')], default='READER', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
